# Generated by Django 6.0.4 on 2026-04-18 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolaccountprofile',
            old_name='school_id',
            new_name='udise_code',
        ),
    ]
