# Generated by Django 6.0.4 on 2026-04-18 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('week_start_date', models.DateField(db_index=True)),
                ('week_end_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed')], db_index=True, default='DRAFT', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin or DEO who reviewed this report.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='schools.school')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weekly Report',
                'verbose_name_plural': 'Weekly Reports',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeeklyPlumbingReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('total_taps', models.PositiveIntegerField(default=0)),
                ('functional_taps', models.PositiveIntegerField(default=0)),
                ('leakage_points_count', models.PositiveIntegerField(default=0)),
                ('drainage_blockage', models.BooleanField(default=False)),
                ('water_availability', models.BooleanField(default=True)),
                ('water_shortage_days', models.PositiveIntegerField(default=0)),
                ('toilet_water_issue', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, default='')),
                ('weekly_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plumbing_report', to='reports.weeklyreport')),
            ],
            options={
                'verbose_name': 'Weekly Plumbing Report',
                'verbose_name_plural': 'Weekly Plumbing Reports',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeeklyIssues',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('issue_type', models.CharField(choices=[('PLUMBING', 'Plumbing'), ('ELECTRICAL', 'Electrical'), ('STRUCTURAL', 'Structural')], db_index=True, max_length=15)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], db_index=True, default='LOW', max_length=10)),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('weekly_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='reports.weeklyreport')),
            ],
            options={
                'verbose_name': 'Weekly Issue',
                'verbose_name_plural': 'Weekly Issues',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeeklyElectricalReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('total_fans', models.PositiveIntegerField(default=0)),
                ('functional_fans', models.PositiveIntegerField(default=0)),
                ('total_lights', models.PositiveIntegerField(default=0)),
                ('functional_lights', models.PositiveIntegerField(default=0)),
                ('power_outage_hours', models.FloatField(default=0, help_text='Total hours of power outage during the week.')),
                ('backup_available', models.BooleanField(default=False)),
                ('wiring_issues', models.BooleanField(default=False)),
                ('switchboard_issues', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, default='')),
                ('weekly_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='electrical_report', to='reports.weeklyreport')),
            ],
            options={
                'verbose_name': 'Weekly Electrical Report',
                'verbose_name_plural': 'Weekly Electrical Reports',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeeklyStructuralReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('classrooms_total', models.PositiveIntegerField(default=0)),
                ('classrooms_usable', models.PositiveIntegerField(default=0)),
                ('roof_leakage', models.BooleanField(default=False)),
                ('wall_cracks', models.BooleanField(default=False)),
                ('plaster_damage', models.BooleanField(default=False)),
                ('building_safety', models.CharField(choices=[('SAFE', 'Safe'), ('MINOR_RISK', 'Minor Risk'), ('UNSAFE', 'Unsafe')], db_index=True, default='SAFE', max_length=15)),
                ('repair_required', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, default='')),
                ('weekly_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='structural_report', to='reports.weeklyreport')),
            ],
            options={
                'verbose_name': 'Weekly Structural Report',
                'verbose_name_plural': 'Weekly Structural Reports',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='weeklyreport',
            constraint=models.UniqueConstraint(fields=('school', 'week_start_date', 'week_end_date'), name='uq_weekly_report_school_week'),
        ),
    ]
