# Generated by Django 6.0.4 on 2026-04-18 10:04

import common.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('udise_code', models.CharField(db_index=True, help_text='Government-issued unique school identifier.', max_length=20, unique=True, verbose_name='UDISE Code')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('address', models.TextField()),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('block', models.CharField(blank=True, default='', max_length=100)),
                ('cluster', models.CharField(blank=True, default='', max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('school_type', models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('HIGHER_SECONDARY', 'Higher Secondary')], db_index=True, default='PRIMARY', max_length=20)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolInfrastructure',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('survey_date', models.DateField(db_index=True)),
                ('boys_toilets_total', models.PositiveIntegerField(default=0)),
                ('boys_toilets_functional', models.PositiveIntegerField(default=0)),
                ('girls_toilets_total', models.PositiveIntegerField(default=0)),
                ('girls_toilets_functional', models.PositiveIntegerField(default=0)),
                ('water_source_available', models.BooleanField(default=False)),
                ('water_quality_ok', models.BooleanField(default=False)),
                ('electricity_connection', models.BooleanField(default=False)),
                ('power_backup', models.BooleanField(default=False)),
                ('leakage_present', models.BooleanField(default=False)),
                ('drainage_issue', models.BooleanField(default=False)),
                ('wiring_condition', models.CharField(choices=[('GOOD', 'Good'), ('AVERAGE', 'Average'), ('POOR', 'Poor')], default='GOOD', max_length=10)),
                ('fan_condition', models.CharField(choices=[('GOOD', 'Good'), ('AVERAGE', 'Average'), ('POOR', 'Poor')], default='GOOD', max_length=10)),
                ('lighting_condition', models.CharField(choices=[('GOOD', 'Good'), ('AVERAGE', 'Average'), ('POOR', 'Poor')], default='GOOD', max_length=10)),
                ('building_condition', models.CharField(choices=[('GOOD', 'Good'), ('MINOR_DAMAGE', 'Minor Damage'), ('MAJOR_DAMAGE', 'Major Damage')], default='GOOD', max_length=15)),
                ('roof_leakage', models.BooleanField(default=False)),
                ('wall_cracks', models.BooleanField(default=False)),
                ('toilet_cleanliness', models.PositiveSmallIntegerField(default=3, help_text='Rating 1 (worst) to 5 (best).', validators=[common.validators.validate_rating])),
                ('campus_cleanliness', models.PositiveSmallIntegerField(default=3, help_text='Rating 1 (worst) to 5 (best).', validators=[common.validators.validate_rating])),
                ('inspection_score', models.FloatField(blank=True, help_text='Auto-computed or manually entered overall score.', null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure_surveys', to='schools.school')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='infrastructure_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Infrastructure',
                'verbose_name_plural': 'School Infrastructure Records',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('total_boys', models.PositiveIntegerField(default=0)),
                ('total_girls', models.PositiveIntegerField(default=0)),
                ('teachers_count', models.PositiveIntegerField(default=0)),
                ('non_teaching_staff_count', models.PositiveIntegerField(default=0)),
                ('classrooms_count', models.PositiveIntegerField(default=0)),
                ('functional_classrooms', models.PositiveIntegerField(default=0)),
                ('area_type', models.CharField(choices=[('RURAL', 'Rural'), ('URBAN', 'Urban'), ('SEMI_URBAN', 'Semi-Urban')], default='RURAL', max_length=15)),
                ('electricity_available', models.BooleanField(default=False)),
                ('internet_available', models.BooleanField(default=False)),
                ('drinking_water_available', models.BooleanField(default=False)),
                ('academic_year', models.CharField(help_text='Format: 2025-2026', max_length=9)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='schools.school')),
            ],
            options={
                'verbose_name': 'School Profile',
                'verbose_name_plural': 'School Profiles',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
