# Generated by Django 6.0.4 on 2026-04-18 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='building_age',
            field=models.PositiveIntegerField(default=5, help_text='Age of the school building in years.'),
        ),
        migrations.AddField(
            model_name='school',
            name='flood_prone_area',
            field=models.BooleanField(default=False, help_text='Whether the school is in a geo-spatially identified flood zone.'),
        ),
        migrations.AddField(
            model_name='school',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='is_girls_school',
            field=models.BooleanField(default=False, help_text='Whether the school is specifically for girls (impacts priority weights).'),
        ),
        migrations.AddField(
            model_name='school',
            name='material_type',
            field=models.CharField(choices=[('Brick', 'Brick'), ('Mixed', 'Mixed'), ('RCC', 'RCC'), ('Temporary', 'Temporary')], db_index=True, default='RCC', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='weather_zone',
            field=models.CharField(choices=[('Coastal', 'Coastal'), ('Dry', 'Dry'), ('Heavy Rain', 'Heavy Rain'), ('Tribal', 'Tribal')], db_index=True, default='Dry', max_length=20),
        ),
        migrations.AddField(
            model_name='schoolinfrastructure',
            name='crack_width_mm',
            field=models.FloatField(default=0.0, help_text='Maximum crack width measured in millimeters (required for ML structural model).'),
        ),
        migrations.CreateModel(
            name='SchoolRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_school_requests', to=settings.AUTH_USER_MODEL)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_request', to='schools.school')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_registration_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Registration Request',
                'verbose_name_plural': 'School Registration Requests',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
