# Generated by Django 6.0.4 on 2026-04-18 15:00

import apps.contracts.models
import common.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('predictions', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('PLUMBING', 'Plumbing'), ('ELECTRICAL', 'Electrical'), ('STRUCTURAL', 'Structural')], db_index=True, max_length=15)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[common.validators.validate_positive])),
                ('priority_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], db_index=True, default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_BIDDING', 'In Bidding'), ('AWARDED', 'Awarded'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=15)),
                ('bid_start_date', models.DateField(blank=True, null=True)),
                ('bid_end_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(help_text='Admin or DEO who created this contract.', on_delete=django.db.models.deletion.PROTECT, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
                ('prediction_report', models.ForeignKey(blank=True, help_text='The prediction report that triggered this contract.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='predictions.predictionreport')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='schools.school')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractBid',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[common.validators.validate_positive])),
                ('estimated_days', models.PositiveIntegerField(help_text='Estimated number of days to complete the work.')),
                ('proposal_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='PENDING', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='contracts.contract')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='accounts.contractorprofile')),
            ],
            options={
                'verbose_name': 'Contract Bid',
                'verbose_name_plural': 'Contract Bids',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractAssignment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[common.validators.validate_positive])),
                ('final_deadline', models.DateField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='contracts.contract')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='accounts.contractorprofile')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment', to='contracts.contractbid')),
            ],
            options={
                'verbose_name': 'Contract Assignment',
                'verbose_name_plural': 'Contract Assignments',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractPayment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[common.validators.validate_positive])),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], db_index=True, default='PENDING', max_length=10)),
                ('transaction_reference', models.CharField(blank=True, default='', help_text='Bank or UPI transaction reference number.', max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Contract Payment',
                'verbose_name_plural': 'Contract Payments',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkProgress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0, help_text='Percentage of work completed (0–100).', validators=[common.validators.validate_percentage])),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed')], db_index=True, default='NOT_STARTED', max_length=15)),
                ('update_note', models.TextField(blank=True, default='')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='contracts.contract')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Progress',
                'verbose_name_plural': 'Work Progress Updates',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkProof',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('file', models.FileField(help_text='Upload image, video, or document as proof of work.', upload_to=apps.contracts.models.work_proof_upload_to, validators=[common.validators.FileSizeValidator(max_mb=10), common.validators.FileExtensionValidator()])),
                ('file_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document')], db_index=True, max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='contracts.contract')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_proofs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Proof',
                'verbose_name_plural': 'Work Proofs',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkVerification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10)),
                ('remarks', models.TextField(blank=True, default='')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='contracts.contract')),
                ('verified_by', models.ForeignKey(help_text='DEO or official who verified the work.', on_delete=django.db.models.deletion.PROTECT, related_name='work_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Verification',
                'verbose_name_plural': 'Work Verifications',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='contractbid',
            constraint=models.UniqueConstraint(fields=('contract', 'contractor'), name='uq_contract_bid_contractor'),
        ),
    ]
