# Generated by Django 6.0.4 on 2026-04-19 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contractassignment_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
